import React, { useState, useMemo } from 'react';

export default function FolderGenerator() {
  const [nameInput, setNameInput] = useState('');
  const [copied, setCopied] = useState(false);

  const folderNames = useMemo(() => {
    return nameInput.split('\n').map(n => n.trim()).filter(n => n.length > 0);
  }, [nameInput]);

  const generatedScript = useMemo(() => {
    if (folderNames.length === 0) return '';
    return '@echo off\nREM Folder Creation Script\nREM Generated by Claude Folder Generator\n\n' + 
      folderNames.map(n => `if not exist "${n.replace(/"/g, '')}" mkdir "${n.replace(/"/g, '')}"`).join('\n') + 
      '\n\necho Created ' + folderNames.length + ' folder(s) successfully!\npause';
  }, [folderNames]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const dataUrl = 'data:text/plain;charset=utf-8,' + encodeURIComponent(generatedScript);
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = 'create-folders.bat';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="min-h-screen p-6" style={{ background: 'linear-gradient(135deg, #FEF7F0 0%, #FFF8F3 50%, #FEF3EB 100%)' }}>
      <div className="max-w-xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #E07A4B, #D96C3B)', boxShadow: '0 4px 12px rgba(217, 108, 59, 0.3)' }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
            </svg>
          </div>
          <div>
            <h1 className="text-xl font-semibold" style={{ color: '#3D2E24' }}>Folder Generator</h1>
            <p className="text-sm" style={{ color: '#8C7A6B' }}>Create a .bat script to batch-generate folders</p>
          </div>
        </div>

        {/* Main Card */}
        <div className="bg-white rounded-2xl p-6" style={{ boxShadow: '0 4px 24px rgba(61, 46, 36, 0.08)', border: '1px solid rgba(217, 108, 59, 0.08)' }}>
          {/* Input */}
          <div className="mb-5">
            <div className="flex justify-between mb-2">
              <label className="text-xs font-semibold uppercase tracking-wide" style={{ color: '#6B5A4D' }}>Folder names</label>
              <span className="text-xs" style={{ color: '#A89888' }}>One per line</span>
            </div>
            <textarea
              value={nameInput}
              onChange={(e) => setNameInput(e.target.value)}
              placeholder={'Documents\nPhotos\nProjects\nBackups'}
              className="w-full h-36 p-3 rounded-xl text-sm font-mono resize-y"
              style={{ 
                border: '2px solid #E8DDD4', 
                background: '#FDFBF9', 
                color: '#3D2E24',
                lineHeight: 1.6,
                outline: 'none'
              }}
              onFocus={(e) => e.target.style.borderColor = '#D96C3B'}
              onBlur={(e) => e.target.style.borderColor = '#E8DDD4'}
            />
          </div>

          {/* Preview Tags */}
          {folderNames.length > 0 && (
            <div className="mb-5">
              <label className="block text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: '#6B5A4D' }}>
                Preview ({folderNames.length} folder{folderNames.length !== 1 ? 's' : ''})
              </label>
              <div className="flex flex-wrap gap-2">
                {folderNames.slice(0, 15).map((name, i) => (
                  <span 
                    key={i} 
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium"
                    style={{ background: 'rgba(217, 108, 59, 0.1)', color: '#D96C3B' }}
                  >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
                    </svg>
                    {name}
                  </span>
                ))}
                {folderNames.length > 15 && (
                  <span className="px-3 py-1.5 rounded-lg text-xs font-medium" style={{ background: '#F5EDE7', color: '#8C7A6B' }}>
                    +{folderNames.length - 15} more
                  </span>
                )}
              </div>
            </div>
          )}

          {/* Generated Script */}
          {generatedScript ? (
            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="text-xs font-semibold uppercase tracking-wide" style={{ color: '#6B5A4D' }}>Generated script</label>
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="px-3 py-2 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all"
                    style={{ 
                      background: copied ? '#22C55E' : 'linear-gradient(135deg, #E07A4B, #D96C3B)', 
                      color: 'white',
                      border: 'none',
                      cursor: 'pointer'
                    }}
                  >
                    {copied ? (
                      <>
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                          <polyline points="20 6 9 17 4 12"/>
                        </svg>
                        Copied!
                      </>
                    ) : (
                      <>
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <rect x="9" y="9" width="13" height="13" rx="2"/>
                          <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                        </svg>
                        Copy
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="px-3 py-2 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all"
                    style={{ 
                      background: 'white',
                      color: '#D96C3B',
                      border: '2px solid #D96C3B',
                      cursor: 'pointer'
                    }}
                  >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
                      <polyline points="7 10 12 15 17 10"/>
                      <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                    Download
                  </button>
                </div>
              </div>
              <pre 
                className="rounded-xl p-4 overflow-auto text-xs font-mono"
                style={{ 
                  background: '#2D2420', 
                  color: '#F5EDE7', 
                  lineHeight: 1.6,
                  maxHeight: '200px'
                }}
              >
                {generatedScript}
              </pre>
            </div>
          ) : (
            <div 
              className="text-center py-10 rounded-xl"
              style={{ background: '#FDFBF9', border: '2px dashed #E8DDD4' }}
            >
              <div 
                className="w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-3"
                style={{ background: 'rgba(217, 108, 59, 0.1)' }}
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#D96C3B" strokeWidth="1.5">
                  <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
                  <line x1="12" y1="11" x2="12" y2="17"/>
                  <line x1="9" y1="14" x2="15" y2="14"/>
                </svg>
              </div>
              <p className="text-sm font-medium" style={{ color: '#6B5A4D' }}>Enter folder names to generate a script</p>
              <p className="text-xs mt-1" style={{ color: '#A89888' }}>One name per line above</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="text-center mt-6 text-xs" style={{ color: '#A89888' }}>
          Built with Claude • Anthropic
        </div>
      </div>
    </div>
  );
}
